version: '3.8'

services:
  gas-web:
    build: .
    container_name: gas-web
    restart: always
    ports:
      - "8097:3001"
    environment:
      - PORT=3001
      - SUPABASE_URL=https://zavlnqgrhtahddoyfntj.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdmxucWdyaHRhaGRkb3lmbnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NTA1MDEsImV4cCI6MjA4NTAyNjUwMX0.aAPCoZDZHnPnYnTtSKWfetwKSG-SqFM0PTQcmEl1SZc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gas-web.rule=Host(`gas.allanturing.com`)"
      - "traefik.http.routers.gas-web.entrypoints=websecure"
      - "traefik.http.services.gas-web.loadbalancer.server.port=3001"
    networks:
      - default
      - proxy

  gas-api:
    build: ./backend
    container_name: gas-api
    restart: always
    ports:
      - "8095:3000"
      - "8096:3000"
    environment:
      - PORT=3000
      - SUPABASE_URL=https://zavlnqgrhtahddoyfntj.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdmxucWdyaHRhaGRkb3lmbnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NTA1MDEsImV4cCI6MjA4NTAyNjUwMX0.aAPCoZDZHnPnYnTtSKWfetwKSG-SqFM0PTQcmEl1SZc
    networks:
      - default
      - proxy

networks:
  default:
    driver: bridge
  proxy:
    external: true
